# Generated by Django 4.2.16 on 2025-01-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q', models.FloatField()),
                ('Z', models.IntegerField()),
                ('shouli1', models.FloatField()),
                ('μ', models.FloatField()),
                ('m', models.IntegerField()),
                ('Z1', models.IntegerField()),
                ('kf', models.FloatField()),
                ('R', models.FloatField()),
                ('shouli2', models.FloatField()),
                ('Z3', models.IntegerField()),
                ('shouli3', models.FloatField()),
                ('T', models.FloatField()),
                ('shouli4', models.FloatField()),
                ('r_values', models.JSONField()),
            ],
        ),
    ]
